[package]
name = "mcp-rust-client-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
mcp-rust-sdk = "=0.1.5"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
mockall = "0.11.0" 